name: issues workflow
on:
  issues: 
    types: [opened]
jobs:
  event-details:
    runs-on: ubuntu-latest
    steps:
      - name: output details
        run: echo "Event object: ${{ toJSON(github.event) }}"

